# Generated by Django 3.1.7 on 2021-03-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brain_tumor_detection', '0002_auto_20210319_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='getImage',
        ),
    ]
